webtalk_init -webtalk_dir C:\\TEMP\\3610_4\\TP4\\TP4.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-04-16 16:42:31" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174126023_174126024_207295007_909" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8v2s691ua68b9ku7uh1qndbi6v" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.2_7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2926 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1523908816408" -context "sdk\\\\bsp/1523908816408"
webtalk_add_data -client sdk -key hwid -value "1523474183050" -context "sdk\\\\bsp/1523908816408"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1523908816408"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1523908816408"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1523908816408"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1523911351512"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1523911351512"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1523911351512"
webtalk_add_data -client sdk -key DebugCount -value "3" -context "sdk\\\\bsp/1523911351512"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1523911351512"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1523911351512"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1523911351512"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1523911351512"
webtalk_transmit -clientid 190407101 -regid "174126023_174126024_207295007_909" -xml C:\\TEMP\\3610_4\\TP4\\TP4.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\TEMP\\3610_4\\TP4\\TP4.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\TEMP\\3610_4\\TP4\\TP4.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
