# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/TEMP/3610_4/TP4/TP4.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_76M_1/design_1_rst_ps7_0_76M_1.xci
# IP: The module: 'design_1_rst_ps7_0_76M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/TEMP/3610_4/TP4/TP4.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_76M_1/design_1_rst_ps7_0_76M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_76M_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/TEMP/3610_4/TP4/TP4.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_76M_1/design_1_rst_ps7_0_76M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_76M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/TEMP/3610_4/TP4/TP4.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_76M_1/design_1_rst_ps7_0_76M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_76M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/TEMP/3610_4/TP4/TP4.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_76M_1/design_1_rst_ps7_0_76M_1.xci
# IP: The module: 'design_1_rst_ps7_0_76M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/TEMP/3610_4/TP4/TP4.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_76M_1/design_1_rst_ps7_0_76M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_76M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/TEMP/3610_4/TP4/TP4.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_76M_1/design_1_rst_ps7_0_76M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_76M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/TEMP/3610_4/TP4/TP4.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_76M_1/design_1_rst_ps7_0_76M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_76M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
